title : ice-cold
tagline: Blog Tagline
author :
  name : CT Ye
  email : 312952525@qq.com
  github : username
  twitter : username
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  

plugins:
  sitemap_generator:
    file_name: sitemap.xml
    exclude_id:
      - search.html
    change_frequency_custom_name: changefreq
    priority_custom_variable_name: priority
  google_site_verification: google5823cc9dfbc3cbfb

pages:
  exclude: 'sitemap.xml'
